### ISSUE TITLE
Failing upgrade 3.10.0. (telling DB version is 3.11.0)

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/matomo_ynh#8]
I didn't inspected much yet but, I made this migration saturday, since then I have mails each hours: 

```
ERROR [2019-09-09 12:05:01] 11246  Got invalid response from API request: ?module=API&method=API.get&idSite=1&period=day&date=last4&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:2317:"Your Matomo codebase is running the old version 3.10.0 and we have detected that your Matomo Database has already been upgraded to the newer version 3.11.0. Maybe your Matomo administrators are currently finishing the upgrade process. Please try again in a few minutes. If you still have this issue please contact your Matomo administrator for assistance.  #0 /var/www/matomo/core/FrontController.php(376): Piwik\FrontController-&gt;throwIfPiwikVersionIsOlderThanDBSchema() #1 /var/www/matomo/core/dispatch.php(33): Piwik\FrontController-&gt;init() #2 /var/www/matomo/index.php(27): require_once('/var/www/matomo...') #3 /var/www/matomo/core/CliMulti/RequestCommand.php(79): require_once('/var/www/matomo...') #4 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\CliMulti\RequestCommand-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Piwik\CliMulti\RequestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 [internal function]: Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /var/www/matomo/core/Console.php(98): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /var/www/matomo/core/Access.php(628): Piwik\Console-&gt;Piwik\{closure}() #10 /var/www/matomo/core/Console.php(99): Piwik\Access::doAsSuperUser(Object(Closure)) #11 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/matomo/console(27): Symfony\Component\Console\Application-&gt;run() #13 {main}";}'
ERROR [2019-09-09 12:05:01] 11246  Empty or invalid response '' for website id 1, Time elapsed: 0.376s, skipping
ERROR [2019-09-09 12:05:02] 11246  2 total errors during this script execution, please investigate and try and fix these errors.
                                                                                             
  [Exception]                                                                                    
  2 total errors during this script execution, please investigate and try and fix these errors.  
                                                                                                 
core:archive [--url="..."] [--force-all-websites] [--force-all-periods[="..."]] [--force-timeout-for-periods[="..."]] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--force-periods[="..."]] [--force-date-last-n="..."] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--concurrent-archivers[="..."]] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]]
```

I hope it's a rare issue on upgrade.

**Comment by Christophe31** [comment]
It may be linked to the upgrade #7 .

**Comment by Christophe31** [comment]
(I "fixed" it by updatein matomo_option table values 3.11.0 to 3.10.0 it looks like working now but it does not sound like a good solution ^^, also I read the migration file before, a simple varchar field length updated so it does not look too dangerous to me)

**Comment by manuelleduc** [comment]
For the record, I'm having the same issue.
I didn't intrusively updated the database, so feel free to ask for more details if you know what you are looking for :)

**Comment by Christophe31** [comment]
I have read the 3.11.0 migration file, it a charfield type change (probably simple length change). To me it felt safe to lie the the database.

**Comment by manuelleduc** [comment]
I also did the version substitution trick recently, using the following SQL query on database matoto:

```
UPDATE matomo_option SET option_value = '3.10.0' WHERE option_value='3.11.0';
```

**Comment by ericgaspar** [comment]
closing... please open a new issue if needed
